### PR TITLE
Added German Translation

### PR DESCRIPTION
**Pull request by DahliaSR**
@oduvan reviewed and approved :shipit: 

Closes CheckIO-to-German/Roadmap#26

### CODE REVIEW

**Comment by oduvan** [comment]
@DahliaSR ,

Merged, But can you check. I thing the HTML is a bit different than in Eng version

**Comment by DahliaSR** [comment]
> Merged, But can you check. I thing the HTML is a bit different than in Eng version

yes that' wirght have a look and compare it!

**German:**
german

**English:**
english

**Comment by oduvan** [comment]
Yup. This is what I see. Can we fix it?

**Comment by DahliaSR** [comment]
> Yup. This is what I see. Can we fix it?

Would you like me to change the formatting of the english version so it matches the german version?
Or do you want me to change back to the original formatting?

**Comment by oduvan** [comment]
Back to original.

**Comment by DahliaSR** [comment]
Okay.
Is there a specific reason why you want to keep the original formattin? Just to avoid any need changes to formatting in the future.

**Comment by oduvan** [comment]
I guess the main reason is that translation should keep the original formatting. I didn't think about which one is better. In case we decide to change the formatting we should change all the translations as well.

**Comment by DahliaSR** [comment]
Yeah that's wright.
Even though a good idea, a bit too much for now, reformatting can be done later too.
I'll change it back.

**Comment by oduvan** [comment]
Thank you

**Pull request merged**
